### ISSUE TITLE
improve augur_align performance

### ISSUE THREAD

**Issue by dpark01** [broadinstitute/viral-pipelines#108]
Possibly replace `augur align` invocation with our own `mafft`-based wrappers that take advantage of recent optimizations. Keep existing WDL task for `augur align` (in case we want it later) but add a new task (or modify an existing one) to `interhost.wdl` and use that instead in the main nextstrain workflow(s)

**Comment by tomkinsc** [comment]
One question is whether we should pursue changes to augur upstream to add something like a `--consider_conserved` param to `augur align` that toggles a code path with mafft `--addfragments` and` --keeplength`.

**Comment by dpark01** [comment]
Well one question is whether `augur align` does much other than a specific incantation of mafft. If it doesn't, maybe the best path is just to call mafft ourselves. But if it's doing something special and nextstrainy, pursuing upstream changes may make sense.

**Comment by dpark01** [comment]
Quick note, #112 tangentially addressed this a bit by throwing some more CPU at it (since mafft appears to make good use of available cores).
