### ISSUE TITLE
remove dnanexus runtime limit for beast_gpu

### ISSUE THREAD

**Issue by dpark01** [broadinstitute/viral-pipelines#116]
From @pauloluniyi:

> I just got a notification that the beast run failed because it exceeded the job timeout of 20.000hrs. 
> 
> Is it possible to increase the timeout? I'm running the bayesian analyses for 200 million MCMC steps with parameters and trees sampled every 10000 generations and so it might need to run for longer than 20 hours.

**Comment by dpark01** [comment]
@tomkinsc I see you're working on this in flight -- I'm thinking we should set the timeout to at least 7-10 days.. I've often run BEAST for about a week at a time

**Comment by tomkinsc** [comment]
I've run it for similar times as well, but was hesitant to set a high timeout considering the potential cost one may incur. I'll increase it...
