### ISSUE TITLE
Broken link on README

### ISSUE THREAD

**Issue by Jeltje** [broadinstitute/viral-pipelines#292]
This link at the bottom of viral-pipelines/README.md gets a Server Not Found error:
https://viral-pipelines.readthedocs.io/en/latest/workflows.html

**Comment by tomkinsc** [comment]
Thanks for reporting; I'm guessing this was a transient error with the documentation host, readthedocs.io. [The link](https://viral-pipelines.readthedocs.io/en/latest/workflows.html) is currently loading for me:

<img width="987" alt="Screen Shot 2021-05-06 at 12 52 21 PM" src="https://user-images.githubusercontent.com/53064/117336167-e6af9d80-ae69-11eb-8ad6-d978390b87bb.png">

If it's still not working for you we can investigate further, but it may be something like a firewall or DNS issue from your connection.

**Comment by Jeltje** [comment]
You're right, it works now.
