### ISSUE TITLE
test_inputs-fastq_to_ubam-local.json to run multiple samples at a time 

### ISSUE THREAD

**Issue by mianlee** [broadinstitute/viral-pipelines#412]
Hello :

I was running fastq to ubam.wdl, how do I put multiple samples information into the .json file, so I don't have to run one sample at a time. What is the right format?

Thank you so much !

{
  "fastq_to_ubam.FastqToUBAM.fastq_1": "inputs/SRR11999460_1.fastq.gz",
  "fastq_to_ubam.FastqToUBAM.fastq_2": "inputs/SRR11999460_2.fastq.gz",
  "fastq_to_ubam.FastqToUBAM.sample_name": "SRR11999460",
  "fastq_to_ubam.FastqToUBAM.library_name": "P4"
  }

**Comment by dpark01** [comment]
Hi @mianlee -- most of these WDLs, including `fastq_to_ubam`, were intended as single sample workflows, with multi-sample parallelization intended for the execution platform/environment (e.. Terra or DNAnexus or similar). There's no reason though that you can't wrap this workflow as a subworkflow within a scatter to turn it into a multi-sample if you're using command line environments.
